package ch9k.chat.events;

import ch9k.chat.Contact;
import ch9k.chat.Conversation;
import ch9k.core.ChatApplication;

/**
 * Base event class for all events generated by a Conversation
 * @author Pieter De Baets
 */
public abstract class ConversationEvent extends ContactEvent {
    private transient Conversation conversation;

    /**
     * Create a new ConversionEvent from a conversation
     * @param conversation
     */
    public ConversationEvent(Conversation conversation) {
        super(conversation.getContact());
        this.conversation = conversation;
    }

    /**
     * Create a new ConversionEvent from a contact
     * @param contact
     */
    public ConversationEvent(Contact contact) {
        super(contact);
        this.conversation = null;
    }

    /**
     * Get the conversation
     * @return conversation
     */
    public Conversation getConversation() {
        if(conversation == null) {
            ChatApplication app = ChatApplication.getInstance();
            conversation = app.getConversationManager().getConversation(getContact());
        }
        return conversation;
    }
}
