package ch9k.chat;

import ch9k.eventpool.Event;

/**
 * Base event class for all events generated by a Conversation
 * @author Pieter De Baets
 */
public abstract class ConversationEvent extends Event {
    private Conversation source;

    public ConversationEvent(Conversation source) {
        this.source = source;
    }

    @Override
    public Conversation getSource() {
        return source;
    }
}
